//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace fpdf.Wpf.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("fpdf.Wpf.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modificado.
        /// </summary>
        public static string FileList_ColumnModified {
            get {
                return ResourceManager.GetString("FileList_ColumnModified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome.
        /// </summary>
        public static string FileList_ColumnName {
            get {
                return ResourceManager.GetString("FileList_ColumnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pág..
        /// </summary>
        public static string FileList_ColumnPages {
            get {
                return ResourceManager.GetString("FileList_ColumnPages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tamanho.
        /// </summary>
        public static string FileList_ColumnSize {
            get {
                return ResourceManager.GetString("FileList_ColumnSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} arquivos.
        /// </summary>
        public static string FileList_FilesCount {
            get {
                return ResourceManager.GetString("FileList_FilesCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Limpar Seleção.
        /// </summary>
        public static string FileList_MenuClearSelection {
            get {
                return ResourceManager.GetString("FileList_MenuClearSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imprimir.
        /// </summary>
        public static string FileList_MenuPrint {
            get {
                return ResourceManager.GetString("FileList_MenuPrint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecionar Todos.
        /// </summary>
        public static string FileList_MenuSelectAll {
            get {
                return ResourceManager.GetString("FileList_MenuSelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imprimir Selecionados.
        /// </summary>
        public static string FileList_PrintSelectedTooltip {
            get {
                return ResourceManager.GetString("FileList_PrintSelectedTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Atualizar.
        /// </summary>
        public static string FileList_RefreshTooltip {
            get {
                return ResourceManager.GetString("FileList_RefreshTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buscar PDF....
        /// </summary>
        public static string FileList_SearchPlaceholder {
            get {
                return ResourceManager.GetString("FileList_SearchPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} selecionados.
        /// </summary>
        public static string FileList_SelectedCount {
            get {
                return ResourceManager.GetString("FileList_SelectedCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favorito.
        /// </summary>
        public static string FolderTree_FavoriteMenu {
            get {
                return ResourceManager.GetString("FolderTree_FavoriteMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Navegar.
        /// </summary>
        public static string FolderTree_NavigateTooltip {
            get {
                return ResourceManager.GetString("FolderTree_NavigateTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Digite o caminho....
        /// </summary>
        public static string FolderTree_PathPlaceholder {
            get {
                return ResourceManager.GetString("FolderTree_PathPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Atualizar.
        /// </summary>
        public static string FolderTree_RefreshTooltip {
            get {
                return ResourceManager.GetString("FolderTree_RefreshTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fucking Portable Document Files.
        /// </summary>
        public static string Main_AppTitle {
            get {
                return ResourceManager.GetString("Main_AppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imprimir (Ctrl+P).
        /// </summary>
        public static string Main_PrintTooltip {
            get {
                return ResourceManager.GetString("Main_PrintTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Atualizar (Ctrl+R).
        /// </summary>
        public static string Main_RefreshTooltip {
            get {
                return ResourceManager.GetString("Main_RefreshTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configurações (Ctrl+,).
        /// </summary>
        public static string Main_SettingsTooltip {
            get {
                return ResourceManager.GetString("Main_SettingsTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mostrar/Ocultar Pastas (Ctrl+B).
        /// </summary>
        public static string Main_ToggleTreeTooltip {
            get {
                return ResourceManager.GetString("Main_ToggleTreeTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favoritos.
        /// </summary>
        public static string Network_Favorites {
            get {
                return ResourceManager.GetString("Network_Favorites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disco Local.
        /// </summary>
        public static string Network_LocalDisk {
            get {
                return ResourceManager.GetString("Network_LocalDisk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diretórios de Rede.
        /// </summary>
        public static string Network_NetworkPaths {
            get {
                return ResourceManager.GetString("Network_NetworkPaths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Este PC.
        /// </summary>
        public static string Network_ThisPC {
            get {
                return ResourceManager.GetString("Network_ThisPC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visualização usando o aplicativo padrão do sistema.
        /// </summary>
        public static string PdfViewer_DefaultAppInfo {
            get {
                return ResourceManager.GetString("PdfViewer_DefaultAppInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nenhum arquivo selecionado.
        /// </summary>
        public static string PdfViewer_NoFile {
            get {
                return ResourceManager.GetString("PdfViewer_NoFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abrir no aplicativo padrão.
        /// </summary>
        public static string PdfViewer_OpenDefault {
            get {
                return ResourceManager.GetString("PdfViewer_OpenDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecione um PDF para visualizar.
        /// </summary>
        public static string PdfViewer_SelectPdf {
            get {
                return ResourceManager.GetString("PdfViewer_SelectPdf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Limpar Tudo.
        /// </summary>
        public static string PrintQueue_ClearAll {
            get {
                return ResourceManager.GetString("PrintQueue_ClearAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Limpar Concluídos.
        /// </summary>
        public static string PrintQueue_ClearCompleted {
            get {
                return ResourceManager.GetString("PrintQueue_ClearCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to concluído(s).
        /// </summary>
        public static string PrintQueue_Completed {
            get {
                return ResourceManager.GetString("PrintQueue_Completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cópias:.
        /// </summary>
        public static string PrintQueue_Copies {
            get {
                return ResourceManager.GetString("PrintQueue_Copies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} na fila.
        /// </summary>
        public static string PrintQueue_CountFormat {
            get {
                return ResourceManager.GetString("PrintQueue_CountFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fila de impressão vazia.
        /// </summary>
        public static string PrintQueue_EmptyQueue {
            get {
                return ResourceManager.GetString("PrintQueue_EmptyQueue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to erro(s).
        /// </summary>
        public static string PrintQueue_Errors {
            get {
                return ResourceManager.GetString("PrintQueue_Errors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to na fila.
        /// </summary>
        public static string PrintQueue_InQueue {
            get {
                return ResourceManager.GetString("PrintQueue_InQueue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nenhuma impressora.
        /// </summary>
        public static string PrintQueue_NoPrinter {
            get {
                return ResourceManager.GetString("PrintQueue_NoPrinter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Páginas:.
        /// </summary>
        public static string PrintQueue_Pages {
            get {
                return ResourceManager.GetString("PrintQueue_Pages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imprimir.
        /// </summary>
        public static string PrintQueue_Print {
            get {
                return ResourceManager.GetString("PrintQueue_Print", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imprimir Tudo.
        /// </summary>
        public static string PrintQueue_PrintAll {
            get {
                return ResourceManager.GetString("PrintQueue_PrintAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imprimir este arquivo.
        /// </summary>
        public static string PrintQueue_PrintThis {
            get {
                return ResourceManager.GetString("PrintQueue_PrintThis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remover.
        /// </summary>
        public static string PrintQueue_Remove {
            get {
                return ResourceManager.GetString("PrintQueue_Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ver fila de impressão.
        /// </summary>
        public static string PrintQueue_ViewQueue {
            get {
                return ResourceManager.GetString("PrintQueue_ViewQueue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adicionar diretório.
        /// </summary>
        public static string Settings_AddDirectory {
            get {
                return ResourceManager.GetString("Settings_AddDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aparência.
        /// </summary>
        public static string Settings_Appearance {
            get {
                return ResourceManager.GetString("Settings_Appearance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelar.
        /// </summary>
        public static string Settings_Cancel {
            get {
                return ResourceManager.GetString("Settings_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Limpar Histórico.
        /// </summary>
        public static string Settings_ClearHistory {
            get {
                return ResourceManager.GetString("Settings_ClearHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cópias padrão.
        /// </summary>
        public static string Settings_DefaultCopies {
            get {
                return ResourceManager.GetString("Settings_DefaultCopies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impressora padrão.
        /// </summary>
        public static string Settings_DefaultPrinter {
            get {
                return ResourceManager.GetString("Settings_DefaultPrinter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impressão frente e verso.
        /// </summary>
        public static string Settings_DoubleSided {
            get {
                return ResourceManager.GetString("Settings_DoubleSided", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pastas favoritas.
        /// </summary>
        public static string Settings_FavoriteFolders {
            get {
                return ResourceManager.GetString("Settings_FavoriteFolders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geral.
        /// </summary>
        public static string Settings_General {
            get {
                return ResourceManager.GetString("Settings_General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Idioma.
        /// </summary>
        public static string Settings_Language {
            get {
                return ResourceManager.GetString("Settings_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diretórios de rede.
        /// </summary>
        public static string Settings_NetworkDirectories {
            get {
                return ResourceManager.GetString("Settings_NetworkDirectories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nenhuma pasta favorita.
        /// </summary>
        public static string Settings_NoFavorites {
            get {
                return ResourceManager.GetString("Settings_NoFavorites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nenhum diretório de rede configurado.
        /// </summary>
        public static string Settings_NoNetworkDir {
            get {
                return ResourceManager.GetString("Settings_NoNetworkDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Caminhos.
        /// </summary>
        public static string Settings_Paths {
            get {
                return ResourceManager.GetString("Settings_Paths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impressão.
        /// </summary>
        public static string Settings_Printing {
            get {
                return ResourceManager.GetString("Settings_Printing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pastas recentes.
        /// </summary>
        public static string Settings_RecentFolders {
            get {
                return ResourceManager.GetString("Settings_RecentFolders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lembrar última pasta.
        /// </summary>
        public static string Settings_RememberLastFolder {
            get {
                return ResourceManager.GetString("Settings_RememberLastFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remover.
        /// </summary>
        public static string Settings_Remove {
            get {
                return ResourceManager.GetString("Settings_Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salvar.
        /// </summary>
        public static string Settings_Save {
            get {
                return ResourceManager.GetString("Settings_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mostrar miniaturas.
        /// </summary>
        public static string Settings_ShowThumbnails {
            get {
                return ResourceManager.GetString("Settings_ShowThumbnails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tema.
        /// </summary>
        public static string Settings_Theme {
            get {
                return ResourceManager.GetString("Settings_Theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tamanho das miniaturas.
        /// </summary>
        public static string Settings_ThumbnailSize {
            get {
                return ResourceManager.GetString("Settings_ThumbnailSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configurações.
        /// </summary>
        public static string Settings_Title {
            get {
                return ResourceManager.GetString("Settings_Title", resourceCulture);
            }
        }
    }
}
