//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace fpdf.Wpf.Resources
{
  using System;


  /// <summary>
  ///   A strongly-typed resource class, for looking up localized strings, etc.
  /// </summary>
  // This class was auto-generated by the StronglyTypedResourceBuilder
  // class via a tool like ResGen or Visual Studio.
  // To add or remove a member, edit your .ResX file then rerun ResGen
  // with the /str option, or rebuild your VS project.
  [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
  [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
  public class Strings
  {

    private static global::System.Resources.ResourceManager resourceMan;

    private static global::System.Globalization.CultureInfo resourceCulture;

    [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
    internal Strings()
    {
    }

    /// <summary>
    ///   Returns the cached ResourceManager instance used by this class.
    /// </summary>
    [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
    public static global::System.Resources.ResourceManager ResourceManager
    {
      get
      {
        if (object.ReferenceEquals(resourceMan, null))
        {
          global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("fpdf.Wpf.Resources.Strings", typeof(Strings).Assembly);
          resourceMan = temp;
        }
        return resourceMan;
      }
    }

    /// <summary>
    ///   Overrides the current thread's CurrentUICulture property for all
    ///   resource lookups using this strongly typed resource class.
    /// </summary>
    [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
    public static global::System.Globalization.CultureInfo Culture
    {
      get
      {
        return resourceCulture;
      }
      set
      {
        resourceCulture = value;
      }
    }

    /// <summary>
    ///   Looks up a localized string similar to Modificado.
    /// </summary>
    public static string FileList_ColumnModified
    {
      get
      {
        return ResourceManager.GetString("FileList_ColumnModified", resourceCulture);
      }
    }

    /// <summary>
    ///   Looks up a localized string similar to Nome.
    /// </summary>
    public static string FileList_ColumnName
    {
      get
      {
        return ResourceManager.GetString("FileList_ColumnName", resourceCulture);
      }
    }

    /// <summary>
    ///   Looks up a localized string similar to Pag..
    /// </summary>
    public static string FileList_ColumnPages
    {
      get
      {
        return ResourceManager.GetString("FileList_ColumnPages", resourceCulture);
      }
    }

    /// <summary>
    ///   Looks up a localized string similar to Tamanho.
    /// </summary>
    public static string FileList_ColumnSize
    {
      get
      {
        return ResourceManager.GetString("FileList_ColumnSize", resourceCulture);
      }
    }

    /// <summary>
    ///   Looks up a localized string similar to {0} arquivos.
    /// </summary>
    public static string FileList_FilesCount
    {
      get
      {
        return ResourceManager.GetString("FileList_FilesCount", resourceCulture);
      }
    }

    /// <summary>
    ///   Looks up a localized string similar to Limpar Selecao.
    /// </summary>
    public static string FileList_MenuClearSelection
    {
      get
      {
        return ResourceManager.GetString("FileList_MenuClearSelection", resourceCulture);
      }
    }

    /// <summary>
    ///   Looks up a localized string similar to Imprimir.
    /// </summary>
    public static string FileList_MenuPrint
    {
      get
      {
        return ResourceManager.GetString("FileList_MenuPrint", resourceCulture);
      }
    }

    /// <summary>
    ///   Looks up a localized string similar to Selecionar Todos.
    /// </summary>
    public static string FileList_MenuSelectAll
    {
      get
      {
        return ResourceManager.GetString("FileList_MenuSelectAll", resourceCulture);
      }
    }

    /// <summary>
    ///   Looks up a localized string similar to Imprimir Selecionados.
    /// </summary>
    public static string FileList_PrintSelectedTooltip
    {
      get
      {
        return ResourceManager.GetString("FileList_PrintSelectedTooltip", resourceCulture);
      }
    }

    /// <summary>
    ///   Looks up a localized string similar to Atualizar.
    /// </summary>
    public static string FileList_RefreshTooltip
    {
      get
      {
        return ResourceManager.GetString("FileList_RefreshTooltip", resourceCulture);
      }
    }

    /// <summary>
    ///   Looks up a localized string similar to Buscar PDF....
    /// </summary>
    public static string FileList_SearchPlaceholder
    {
      get
      {
        return ResourceManager.GetString("FileList_SearchPlaceholder", resourceCulture);
      }
    }

    /// <summary>
    ///   Looks up a localized string similar to {0} selecionados.
    /// </summary>
    public static string FileList_SelectedCount
    {
      get
      {
        return ResourceManager.GetString("FileList_SelectedCount", resourceCulture);
      }
    }

    /// <summary>
    ///   Looks up a localized string similar to Idioma.
    /// </summary>
    public static string Settings_Language
    {
      get
      {
        return ResourceManager.GetString("Settings_Language", resourceCulture);
      }
    }

    /// <summary>
    ///   Looks up a localized string similar to Configuracoes.
    /// </summary>
    public static string Settings_Title
    {
      get
      {
        return ResourceManager.GetString("Settings_Title", resourceCulture);
      }
    }
  }
}
